# Generated by Django 3.1.7 on 2021-09-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('salary', models.IntegerField()),
                ('company', models.CharField(max_length=200)),
            ],
        ),
    ]
